# Generated by Django 5.1.4 on 2025-04-02 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIND', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRepere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('nom', models.CharField(max_length=200)),
                ('valeur_theorique', models.FloatField()),
                ('description', models.TextField(blank=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reperes', to='WIND.audit')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ControlRepere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_controle', models.DateTimeField(auto_now_add=True)),
                ('valeur_reelle', models.FloatField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('conforme', 'Conforme'), ('non_conforme', 'Non Conforme'), ('na', 'Non Applicable')], max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='controle_images/')),
                ('repere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='controles', to='WIND.auditrepere')),
            ],
        ),
    ]
