# Generated by Django 5.1.4 on 2025-04-07 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WIND', '0003_utilisateur_avatar_alter_utilisateur_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='admin_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='approval_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='approval_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verification_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verification_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
